### PR TITLE
New rank method

### PR DESCRIPTION
**Pull request by rjschnei**
- Updated rank method so more transparent
- Simplified prediction method
- Unfortunately no longer shows best and worst games, but this could be added later

### CODE REVIEW

**Comment by kersson** [comment]
If we're deleting the original ranking stuff, can you also remove the associated requirements, like Theano, from the `requirements.txt` file?

**Comment by kersson** [comment]
Would be cool to add the win/loss record at some point too.

**Review by cmey — APPROVED** [review]
No need to delete `ranking.py` and `theanorank.py` though.

**Comment by rjschnei** [comment]
Yeah, was trying to "trim the fat" as it were... we can keep them but put them in a folder indicating it is unused.

**Review by kersson — APPROVED** [review]

**Pull request merged**
